import { StyleSheet } from 'react-native';
import { lightColors } from '../shared/colors';

export const createGlobalStyles = (theme = lightColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  box: {
    width: '80%',
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
  },
  section: {
    width: '100%',
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 12,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBox: {
    width: '80%',
    height: 150,
    backgroundColor: theme.secondaryBackground,
    borderRadius: 12,
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.secondaryBackground,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    width: '100%',
    color: theme.text,
  },
  button: {
    backgroundColor: theme.primary,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 5,
  },
  buttonText: {
    color: theme.onPrimary,
    textAlign: 'center',
  },
  link: {
    color: theme.primary,
    textAlign: 'center',
    marginTop: 15,
  },
  error: {
    color: theme.error,
    fontSize: 12,
    marginBottom: 5,
  },
  text: {
    fontSize: 16,
    color: theme.text,
    fontFamily: 'CustomFontRegular',
  },
  headerContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: theme.primary,
  },
  circleButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconLg: {
    width: 30,
    height: 30,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: 'CustomFontBold',
    color: theme.onPrimary,
  },
  optionsContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  iconMd: {
    width: 24,
    height: 24,
  },
  searchInput: {
    flex: 1,
    marginHorizontal: 10,
    backgroundColor: theme.surface,
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
    color: theme.text,
  },
  galleryContainer: {
    flex: 1,
    width: '100%',
  },
  galleryContent: {
    paddingVertical: 10,
  },
  card: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 10,
    margin: 5,
  },
  footerContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  footerButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignItems: 'center',
  },
  cardHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    flex: 1,
    color: theme.text,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 10,
  },
  iconSm: {
    width: 20,
    height: 20,
  },
  cardBody: {
    width: '100%',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: 120,
    borderRadius: 12,
  },
  infoIconContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: theme.surface,
    borderRadius: 20,
  },
  sectionTitle: {
    fontSize: 16,
    color: theme.text,
    fontFamily: 'CustomFontBold',
    marginBottom: 10,
  },
  placeholderBox: {
    width: '100%',
    height: 100,
    backgroundColor: theme.secondaryBackground,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genreContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  genreItem: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
    backgroundColor: theme.secondaryBackground,
  },
  genreItemSelected: {
    backgroundColor: theme.primary,
  },
  genreText: {
    color: theme.text,
  },
  genreTextSelected: {
    color: theme.onPrimary,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  secondaryButtonText: {
    color: theme.text,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: theme.surface,
    borderRadius: 12,
    padding: 20,
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
